name: 'Wait'
description: 'Create a JavaScript Action grade the project'
outputs:
  grade:
    description: 'The output of this file will be a grade and percentage given to the repo.'
runs:
  using: 'node12'
  main: 'dist/index.js'
