name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit-tests:
    if: "!contains(github.event.head_commit.author_name, 'GitHub Action')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm test
      # Generation the new distribution
      - run: npm run package
      - name: package-and-commit
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'dist'
          author_name: 'GitHub Action'
          message: 'Auto-building distribution'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: ./
      with:
        milliseconds: 1000
